# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/api/06_utils.ipynb.

# %% auto 0
__all__ = ['install_pytorch3d']

# %% ../notebooks/api/06_utils.ipynb 4
import subprocess
import sys

import torch


def install_pytorch3d():
    pyt_version_str = torch.__version__.split("+")[0].replace(".", "")
    version_str = "".join(
        [
            f"py3{sys.version_info.minor}_cu",
            torch.version.cuda.replace(".", ""),
            f"_pyt{pyt_version_str}",
        ]
    )
    subprocess.run(["pip", "install", "fvcore", "iopath"])
    subprocess.run(
        [
            "pip",
            "install",
            "--no-index",
            "--no-cache-dir",
            "pytorch3d",
            "-f",
            f"https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html",
        ]
    )
